distributed:
  logging:
    bokeh: critical

  dashboard:
    link: /user/{JUPYTERHUB_USER}/proxy/{port}/status

  admin:
    tick:
      limit: 5s

kubernetes:
  worker-template:
    metadata:
    spec:
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
          - --no-bokeh
          - --memory-limit
          - 6GB
          - --death-timeout
          - '60'
        image: null  # overwrite with env variable
        name: dask-worker
        resources:
          limits:
            cpu: "1.75"
            memory: 2G
          requests:
            cpu: "1.75"
            memory: 2G
